# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_num', models.IntegerField(verbose_name='\u63a7\u5236\u4ee3\u53f7')),
                ('control_statue', models.IntegerField(choices=[(0, '\u5173\u95ed'), (1, '\u5f00\u8d77'), (3, '\u8c03\u8282')], default=0, verbose_name='\u63a7\u5236\u72b6\u6001')),
                ('control_type', models.IntegerField(choices=[(0, '\u5f00\u5173\u63a7\u5236'), (1, '\u5f3a\u5ea6\u63a7\u5236')], verbose_name='\u63a7\u5236\u7c7b\u578b')),
                ('control_name', models.CharField(max_length=30, verbose_name='\u63a7\u5236\u65b9\u6cd5\u540d')),
                ('control_code', models.CharField(max_length=30, verbose_name='\u63a7\u5236\u4ee3\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='./2706179_185025082_2.jpg', upload_to=b'')),
            ],
        ),
    ]
