# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-23 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_num', models.IntegerField(verbose_name='\u63a7\u5236\u4ee3\u53f7')),
                ('control_name', models.CharField(max_length=30, verbose_name='\u63a7\u5236\u65b9\u6cd5\u540d')),
                ('control_code', models.CharField(max_length=30, verbose_name='\u63a7\u5236\u4ee3\u7801')),
            ],
        ),
    ]
