# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='control_statue',
            field=models.IntegerField(default=0, verbose_name='\u63a7\u5236\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='devicecontrol',
            name='control_type',
            field=models.IntegerField(choices=[(0, '\u5f00\u5173'), (1, '\u5f3a\u5ea6\u8c03\u8282')], default=1, verbose_name='\u63a7\u5236\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
