# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='control_deviceName',
            field=models.CharField(default=1, max_length=20, verbose_name='\u8bbe\u5907\u540d\u79f0'),
            preserve_default=False,
        ),
    ]
