# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('illumination', models.IntegerField(default=0)),
                ('capnography', models.IntegerField(default=0)),
                ('data', models.DateField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinuteStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('illumination', models.IntegerField(default=0)),
                ('capnography', models.IntegerField(default=0)),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SittingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='root', max_length=16)),
                ('deviceName', models.CharField(max_length=30)),
                ('sittingContent', models.CharField(default='', max_length=16)),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
